### PR TITLE
Add website to DESCRIPTION

### PR DESCRIPTION
**Pull request by olivroy**
### Intent

Make website more discoverable and enable linking 

### Approach

Add to DESCRIPTION URL field

### Checklist

This is a very minor change, no need to add to news.

Edit: I also removed roxygen2 from Suggests as its import is declared with the `RoxygenNote` field.

### CODE REVIEW

**Comment by RasmusSkytte** [comment]
This change seems innocent enough.

I am however confused about what is going here.
The comitter has 170 commits across 140 repos in January already.

image

**Comment by olivroy** [comment]
I just think it is worth adding as it helps with discovery and in my opinion, the website is a more pleasant way to read documentation.

**Comment by marcusmunch** [comment]
@olivroy It seems removing roxygen2 from Suggests no longer installs the package, even if passing `dependencies = TRUE` to `install.packages()`. Additionally, we try to adhere to a coding and documentation standard of being explicit rather than implicit, and keeping roxygen2 in Suggests also serves as a way to easily guide new contributors in how to document code additions.

I may be mistaken about whether or not roxygen2 still installs if removed from Suggests. If that is the case, do you have any sources for that?

**Review by LasseEngboChr — APPROVED** [review]

**Comment by olivroy** [comment]
Sure, I added it back. 

I think that the assumption is that roxygen2 is only needed for devs, not for users of the package. Once roxygen2 has documented the package, it has no impact, because CRAN only cares about the generated .Rd files.

Usually, unless stated otherwise, most packages use devtools, but  [do not put it in DESCRIPTION](https://r-pkgs.org/dependencies-mindset-background.html#sec-dependencies-tidyverse)

Out of the ~ [13,000 CRAN packages that are documented with roxygen2](https://github.com/search?q=org%3Acran%20RoxygenNote&type=code), there are only about 70 that list roxygen2 in Suggests.

**Pull request merged**
